name: tensorflow-arc
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libsqlite=3.47.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.10.16
  - readline=8.2
  - setuptools=75.6.0
  - tk=8.6.13
  - tzdata=2024b
  - wheel=0.45.1
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.5.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - flatbuffers==24.12.23
      - gast==0.6.0
      - google-auth==2.37.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - idna==3.10
      - intel-extension-for-tensorflow==2.15.0.2
      - intel-extension-for-tensorflow-lib==2.15.0.2.2
      - keras==2.15.0
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==3.0.2
      - ml-dtypes==0.2.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.4.0
      - packaging==24.2
      - protobuf==4.23.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - six==1.17.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wget==3.2
      - wrapt==1.14.1
